first check
DamianPasterz/videoDb pull request #4
Opened 2023-03-09 13:23 UTC by DamianPasterz

2023-03-09 14:04 UTC, GrzegorzDryja requested changes

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/app.component.scss
>  }
Brak linii na końcu.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/app.module.ts
>  import { StoreModule } from '@ngrx/store';
Do góry.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/app.module.ts
> +import { FormsModule } from '@angular/forms';
Do góry.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/models/input.model.ts
> +}
Dodaj pustą linię na końcu.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/models/matching.models.ts
> +export const YOUTUBE_ONLY_ID_CHECK = new RegExp(/^[a-zA-Z0-9_.-]{11}$/);
Dodaj pustą linię na końcu.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/models/videoServices.model.ts
> +}
Pusta linia.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/services/input.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
Plik do usunięcia jak nie robisz testów.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/services/input.service.ts
> +  constructor() {}
Daj odstęp. I ogólnie jak nie wykorzystujesz constructora to do usunięcia.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/core/services/input.service.ts
> +      return this.inputData
Coś tutaj śmierdzi. Nie musisz zwracać tych danych, albo zwracasz rezultat albo modyfikujesz zmienną, do której możesz się możesz odwołać w ramach DI. Ale jeżeli nie odwołujesz do zmiennej globalnie to możesz ją umieścić w ramach funkcji.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/favourite-bar/favourite-bar.component.scss
> +    padding: 15px;
Warto dać odstęp.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/favourite-bar/favourite-bar.component.scss
> +  &__example-spacer {
Tu też.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/home/home.component.scss
>  }
Brak pustej linii.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/material.module.ts
> +export class MaterialModule {}
Brak pustej linii.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.scss
> +  &__input {
Odstęp.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.scss
> +  &__button {
Odstęp.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.scss
> +    &:hover {
Odstęp.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.scss
> +  &__alert {
Odstęp.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Do usunięcia.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> +public ngOnInit():void {
Wcięcie.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> +public onAddvideo(form: NgForm){
Wcięcie, odstęp, camelCase.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> +  console.log(form);
Console log do wywalenia.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> +  const videoData = this.inputService.onProviderAndIdCheck(form.value.value)
Formatowanie tekstu.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-contanier/videos-contanier.component.html
> +<mat-card class="videosContanier">
Kebab.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-contanier/videos-contanier.component.scss
> +}
Brak pustej linii.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-contanier/videos-contanier.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Do usunięcia.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-item/videos-item.component.html
> +    mat-card-image
Wydaje mi się, że powinno zadziałać bez img.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-item/videos-item.component.scss
> +}
Brak pustej linii.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/videos-item/videos-item.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Do usunięcia, jak nie testujesz.

2023-03-09 14:04 UTC, GrzegorzDryja commented on tsconfig.json
> +    "strict": false,
:]

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/styles.scss
> +$grean2: rgba(135,140,2,1);
Nie wiem co z tym, w sumie spoko, że globalne, ale nie jestem pewny tej implementacji.

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> + this.inputService.onProviderAndIdCheck("")
Czemu to robisz w ngOnInit?

2023-03-09 14:04 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.html
> +				#inputUrlField="ngModel"
Wydaje mi się, że jest to zbędne.

2023-03-09 14:18 UTC, DamianPasterz commented on src/app/videos-item/videos-item.component.html
> +    mat-card-image
potestuje

2023-03-09 14:20 UTC, DamianPasterz commented on src/styles.scss
> +$grean2: rgba(135,140,2,1);
to w sumie nie działa tak jak bym chciał :D

2023-03-09 14:21 UTC, DamianPasterz commented on src/app/search-bar/search-bar.component.ts
> + this.inputService.onProviderAndIdCheck("")
nie wiem :D

2023-03-09 14:21 UTC, DamianPasterz commented on src/app/search-bar/search-bar.component.html
> +				#inputUrlField="ngModel"
do walidacji używam

2023-03-09 14:22 UTC, DamianPasterz commented
musze eslinta i prettiera lepiej skonfigurować :D

2023-03-09 15:00 UTC, GrzegorzDryja approved these changes

2023-03-09 15:00 UTC, GrzegorzDryja commented on src/app/core/services/input.service.ts
> +    }else return  this.inputData={provider: VideoServices.incorect, id: null}
Musisz określić co ten serwis ma robić. Czy modyfikować zmienną do której się odwołujesz czy zwracasz to. Jeżeli chcesz coś zwracać to inputData nie jest potrzeba. Dopisz również co funkcja ma zwracać.  Jeżeli nie chcesz nic zwracać to funkcja jest void. A inputData może mieć domyślną wartość.
Plus formatowanie.

2023-03-09 15:00 UTC, GrzegorzDryja commented on src/app/search-bar/search-bar.component.ts
> +  constructor(private inputService: InputService){}
Jeszcze formatowanie by się przydało w kilku miejscach wrzucić.

2023-03-09 15:00 UTC, GrzegorzDryja commented on src/app/core/models/matching.models.ts
> +}
Się zastanawiałem nad tym, ale jednak warto by oddzielić te stałe.

2023-03-09 22:12 UTC, bronasek commented on src/app/core/models/input.model.ts
> +  id: string | null
średniki na końcu, a nie przecinek

2023-03-09 22:13 UTC, bronasek commented on src/app/core/models/input.model.ts
> +  id: string | null
na providera moznaby chyba enuma stworzyc i tu wrzucic zamiast string?

2023-03-09 22:15 UTC, bronasek commented on src/app/core/models/matching.models.ts
> +}
nie uzywalbym enuma do takich stałych, daj zwyaczjny obiekt, albo osobne stałe

2023-03-09 22:15 UTC, bronasek commented on src/app/core/models/video.model.ts
> +  platform: string;
czy platform to to samo co provider?

2023-03-09 22:15 UTC, bronasek commented on src/app/core/models/videoServices.model.ts
> +export enum VideoServices {
ooo no i tego moznaby chyba uzyc zamiast stringa w platform czy provider?

2023-03-09 22:17 UTC, bronasek commented on src/app/search-bar/search-bar.component.ts
> +  public minInput = machingPiont.minInput
maching czy matching?

2023-03-09 22:19 UTC, bronasek commented on src/app/search-bar/search-bar.component.ts
> +  public showValidateErrors: boolean
nazwa jak przy metodzie
isValidationErrorVisible ?

2023-03-09 22:19 UTC, bronasek commented on src/app/search-bar/search-bar.component.ts
> +  public ngOnInit(): void {}
jak nic tu nie ma to mozna wywalic

2023-03-09 22:22 UTC, bronasek commented on src/app/videos-item/videos-item.component.scss
> +.videoContanier {
kebab case zamiast camel case
kebab powinien być Ci bliski

2023-03-10 09:00 UTC, DamianPasterz commented on src/app/videos-item/videos-item.component.scss
> +.videoContanier {
wczoraj jadłem naprawdę dobry kebab :D

2023-03-10 11:28 UTC, bronasek commented on src/app/core/models/input.model.ts
> +  provider: string;
ale to czekaj, bo pytalem chyba o to
tu nie mozemy wrzucic VideoServices? czy ma byc string?

2023-03-10 11:30 UTC, bronasek approved these changes

2023-03-10 11:56 UTC, merged